### ISSUE TITLE
 sampleCbModel > mve_solver_cobra (interior point x0; is not interior) 

### ISSUE THREAD

**Issue by jennmodamio** [Bounciness/Volume-and-Sampling#4]
Around 1 month ago (even less) the following piece of code was working fine:  

```
options.nStepsPerPoint = 10000;
options.nPointsReturned = 10000;
options.toRound = 1;
[P_WT_modelSec , S_WT_modelSec] = sampleCbModel(modelSec, [], [], options);
```

However now I get the following error: 

```
Error using mve_solver_cobra (line 29)
x0 not interior
Error in mve_run_cobra (line 32)
    [x,E2,converged] = mve_solver_cobra(A,b,x0,maxiter,tol2,reg); %Ben
Error in preprocess (line 250)
            [T_shift, Tmve,converged] = mve_run_cobra(P.A,P.b, x0,reg);
Error in chrrSampler (line 110)
    [roundedPolytope] = preprocess(P,options);
Error in sampleCbModel (line 162)
        [samples, modelSampling] = chrrSampler(model, nStepsPerPoint, nPointsReturned, toRound, modelSampling, useFastFVA,optPercentage);
```

**Comment by Bounciness** [comment]
Hi Jennifer, 

Thanks for reporting the error, sorry I broke it. Would you mind sharing which LP solver you are using?

Best,
Ben

**Comment by jennmodamio** [comment]
Hello Ben, 

Thanks for your help. I am using Gurobi. 

Best, 
Jennifer

**Comment by Bounciness** [comment]
Can you try again? I think it should be working again. (Just update the Volume-and-Sampling submodule)

**Comment by laurentheirendt** [comment]
@Bounciness, every time you update your repo, may you also submit a pull request to `opencobra/cobratoolbox` in order to update the SHA1 of your submodule? Thanks 👍

**Comment by Bounciness** [comment]
@laurentheirendt Yes, absolutely I can Thanks for letting me know (and for taking care of it this time).

**Comment by josh-lewis** [comment]
I recently started using sampleCbModel and have run into the same error as @jennmodamio 
```
Error using mve_solver_cobra (line 29)
x0 not interior
Error in mve_run_cobra (line 32)
    [x,E2,converged] = mve_solver_cobra(A,b,x0,maxiter,tol2,reg); %Ben
Error in preprocess (line 250)
            [T_shift, Tmve,converged] = mve_run_cobra(P.A,P.b, x0,reg);
Error in chrrSampler (line 110)
    [roundedPolytope] = preprocess(P,options);
Error in sampleCbModel (line 162)
        [samples, modelSampling] = chrrSampler(model, nStepsPerPoint, nPointsReturned, toRound, modelSampling, useFastFVA,optPercentage);
```
I am also using the Gurobi LP solver (version 7.0). Is this still a known error?

**Comment by laurentheirendt** [comment]
@josh-lewis, are you using the latest version of the COBRA Toolbox?

**Comment by josh-lewis** [comment]
Yes, I downloaded the most recent version a few days ago (as well as the most recent version of Volume-and-Sampling)

**Comment by laurentheirendt** [comment]
@Bounciness, maybe this error message is not explicit enough. It doesn't provide a way of how to proceed, i.e. how to choose `x0` such that `x0 is interior`. Eventually, may you change this error message?

**Comment by Bounciness** [comment]
Yes, I can alter the error message to suggest some ways to fix it. Sometimes you can fiddle with the parameters to get the preprocessing to finish. 

@josh-lewis I'm happy to test out your specific model to suggest how to proceed. I'd like to make sure that whatever alterations I do to the code end up being able to sample your model.

**Comment by josh-lewis** [comment]
[model_test.zip](https://github.com/Bounciness/Volume-and-Sampling/files/1908284/model_test.zip)
@Bounciness I greatly appreciate your willingness to test out my model. It is in the attached zip folder.

**Comment by josh-lewis** [comment]
@Bounciness thank you again for trying to get my model to work with your code. Were you able to find a fix for the error that I've been running into? Let me know if I can help in any way.
